### ISSUE TITLE
Trying to create a new Design Document with options parameter included in a database Returns: "AttributeError: 'dict' object has no attribute 'to_dict'"

### ISSUE THREAD

**Issue by aanagnostou** [IBM/cloudant-python-sdk#119]
**Describe the bug**

Can not create a Design Document in a database with function: `put_design_document` if you include the options parameter, despite if the value is `True` or `False`

**To Reproduce**

Code snippet slightly different from: [Api Docs](https://cloud.ibm.com/apidocs/cloudant?code=python#putdesigndocument)

```Python
from ibmcloudant.cloudant_v1 import (
    DesignDocument,
    CloudantV1,
    DesignDocumentViewsMapReduce,
    SearchIndexDefinition,
)

try:
    from dotenv import load_dotenv, find_dotenv

    load_dotenv(find_dotenv())
except ModuleNotFoundError as e:
    print("ERROR")

service = CloudantV1.new_instance(service_name="ADMIN")

product_map = DesignDocumentViewsMapReduce(
    map="function(doc) { emit(doc.productid, [doc.brand, doc.name, doc.description]) }"
)

price_index = SearchIndexDefinition(
    index='function (doc) {  index("price", doc.price);}'
)

partitioned_design_doc = DesignDocument(
    views={"byApplianceProdId": product_map},
    indexes={"findByPrice": price_index},
    options={"partitioned": True},
)

response = service.put_design_document(
    db='products',
    design_document=partitioned_design_doc,
    ddoc="appliances",
).get_result()

print(response)
```

**Expected behavior**
                                                                                                
Should return: `{'ok': True, 'id': '_design/appliances', 'rev': '1-**************************************'}`

**Traceback**

``
Traceback (most recent call last):
  File "/home/**/bug1.py", line 31, in <module>
    response = service.put_design_document(
  File "/home/**/venv/lib/python3.8/site-packages/ibmcloudant/cloudant_v1.py", line 2628, in put_design_document
    design_document = convert_model(design_document)
  File "/home/**/venv/lib/python3.8/site-packages/ibm_cloud_sdk_core/utils.py", line 215, in convert_model
    return val.to_dict()
  File "/home/**/venv/lib/python3.8/site-packages/ibmcloudant/cloudant_v1.py", line 10779, in to_dict
    _dict['options'] = self.options.to_dict()
AttributeError: 'dict' object has no attribute 'to_dict'
``

 - SDK Version [Installed with `pip install --upgrade "ibmcloudant>=0.0.34"`]
 - Python Version [e.g. Python 3.8.6]
 - Create a New Design Document

**Additional context**

Knowing that this `design_document = convert_model(design_document)` returns a Dict..

I was able to avoid this problem by changing this line: 

https://github.com/IBM/cloudant-python-sdk/blob/cc169b21832b3db8c2f898edf7dd12c4c91a15ab/ibmcloudant/cloudant_v1.py#L10779

with: `_dict["options"] = self.options`

**Comment by emlaver** [comment]
Hello @aanagnostou, you'll either need to use all model classes or use all dictionaries.  The `options` model class for this endpoint is `DesignDocumentOptions`:
```python
...
design_document_options = DesignDocumentOptions(
    partitioned=True
)
partitioned_design_doc = DesignDocument(
    views={"byApplianceProdId": product_map},
    indexes={"findByPrice": price_index},
    options=design_document_options,
)
...
```
Here's an example if you want to do all dictionaries:
```python
...
product_map = {'map':"function(doc) { emit(doc.productid, [doc.brand, doc.name, doc.description]) }"}
price_index = {'index': 'function (doc) {  index("price", doc.price);}'}
partitioned_design_doc = {
    'views': {"byApplianceProdId": product_map},
    'indexes': {"findByPrice": price_index},
    'options': {"partitioned": True},
)
...
```
Screenshot of `options` for `PUT /{db}/_design/{ddoc}` in [API Docs](https://cloud.ibm.com/apidocs/cloudant?code=python#putdesigndocument):
<img width="576" alt="Screen Shot 2021-06-30 at 10 27 18 AM" src="https://user-images.githubusercontent.com/10552966/123978382-d14c8080-d98d-11eb-8602-7f9d89ec9e27.png">

**Comment by aanagnostou** [comment]
Hi @emlaver ,

Thanks for clarifying that.

As you can imagine it's working as it should.

Thank you for your time
