### ISSUE TITLE
Allow default `db` to be passed to `new_instance`

### ISSUE THREAD

**Issue by jpribyl** [IBM/cloudant-python-sdk#125]
**Is your feature request related to a problem? Please describe.**

Often, I will create a `client` which only must connect to one `db` - in this case, it would improve developer experience to have the ability to set a default `db` which would make the param optional in all instance methods

At present, I have a workaround by overriding all the methods in the class:
```python
class Cloudant(CloudantV1):                                                                       
    DEFAULT_SERVICE_NAME = "cloudant"                                                             
    DB = None                                                                                     

    @classmethod                                                                                  
    def new_instance(                                                                             
        cls,                                                                                      
        service_name: str = DEFAULT_SERVICE_NAME,                                                 
        db: str = None,                                                                           
    ) -> "CloudantV1":                                                                            
        """                                                                                       
        Return a new client for the Cloudant service using the specified parameters               
        and external configuration.                                                        
        """                                                                                       
        authenticator = get_authenticator_from_environment(service_name)                          
        cls.DB = db                                                                               
        service = cls(authenticator)                                                              
        service.configure_service(service_name)                                                   
        return service                                                                            

    def delete_database(self, **kwargs):                                                          
        if self.DB is not None:                                                                   
            return super().delete_database(**kwargs, db=self.DB)                                         
        else:                                                                                     
            return super().delete_database(**kwargs)

    ...

    def put_security(self, **kwargs):                                                          
        if self.DB is not None:                                                                   
            return super().put_security(**kwargs, db=self.DB)                                         
        else:                                                                                     
            return super().put_security(**kwargs)
```
But this is not ideal and requires a lot of boilerplate

**Describe the solution you'd like**

Ideally, `new_instance` would accept an optional param of `db` which would allow us to set a default database name

**Describe alternatives you've considered**

The alternative involves lots of boilerplate code

**Additional context**

N/A

I would be happy to submit a PR for this if it's something y'all are willing to incorporate

**Comment by eiri** [comment]
Hi @jpribyl,

Thank you for your feedback! Since our sdk generated from OpenAPI specs we do not directly modify [number of files](https://github.com/IBM/cloudant-python-sdk/blob/master/CONTRIBUTING.md#prs) including `CloudantV1` class methods, but we'll consider your use case for future enhancements.

**Comment by jpribyl** [comment]
Ahh, I see, thanks for the reply @eiri ! Is there a way for me to contribute to the OpenAPI specs?

This is totally unrelated but as I am using this SDK I am also discovering that the SDK does not seem to have a method allowing me to call a couchdb update handler (IE this endpoint https://docs.couchdb.org/en/latest/api/ddoc/render.html#db-design-design-doc-update-update-name-doc-id)

Do you know if that is in the works for a future version as well? I would be happy to help add in that method + handler too if it's possible!

**Comment by eiri** [comment]
We are planning to open source the specs, but we are not quite there yet, the API changes in the upcoming CouchDB 4.0 mixed our plans a bit. But thank you for your interest, appreciate that!

Yes, we have the coverage of the ddoc's update handler in our TODO queue, but unfortunately no estimate delivery time at the moment.

**Comment by jpribyl** [comment]
Awesome, thanks again for the replies and all the work y'all have put into this. I'm really excited to see where this project goes. We just added couch to our stack so I'll be sure to keep an eye out for updates!
