### ISSUE TITLE
Incorrect typing for `validate_doc_update` param in `cloudant_v1`

### ISSUE THREAD

**Issue by jpribyl** [IBM/cloudant-python-sdk#126]
**Describe the bug**
SDK types `validate_doc_update` as a dict in several places:
https://github.com/IBM/cloudant-python-sdk/blob/4b4ed1fb173a240b0a6b1b842c5154d064ee2051/ibmcloudant/cloudant_v1.py#L10569
https://github.com/IBM/cloudant-python-sdk/blob/4b4ed1fb173a240b0a6b1b842c5154d064ee2051/ibmcloudant/cloudant_v1.py#L10596
https://github.com/IBM/cloudant-python-sdk/blob/4b4ed1fb173a240b0a6b1b842c5154d064ee2051/ibmcloudant/cloudant_v1.py#L10630

A design doc may only have one `validate_doc_update` function and it must be a string:
https://github.com/apache/couchdb/blob/main/src/couch_views/src/couch_views_validate.erl#L260

[permalink](https://github.com/apache/couchdb/blob/647aea29ce8431fa5c2049cc6da47a9305ad3e6b/src/couch_views/src/couch_views_validate.erl#L260) in case it moves

**To Reproduce**

None, easily visible above

**Expected behavior**

Typing should be correct

**Screenshots**

**Must gather (please complete the following information):**
I don't think any of these are necessary here, but 
 - ibm-cloud-sdk-core==3.10.0 with ibmcloudant==0.0.34
 - Python 3.9.6
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**

**Comment by mojito317** [comment]
@jpribyl, thanks for reporting this!

**Comment by vmatyusGitHub** [comment]
Fixed in version [0.0.37](https://github.com/IBM/cloudant-python-sdk/releases/tag/v0.0.37)
