### ISSUE TITLE
ModuleNotFoundError 'ibm_cloud_sdk_core.token_manager' on import

### ISSUE THREAD

**Issue by Patschke** [IBM/cloudant-python-sdk#136]
**Describe the bug**
On attempt to import ibmcloudant a Module not Found error is raised. 

**To Reproduce**
On a clean with the latest cloudant-python-sdk and python-sdk-core importing ibmcloudant fails. Here the output from a ipython console: 
```
$ ipython
Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import ibmcloudant
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5b4cad6fa19a> in <module>
----> 1 import ibmcloudant

/usr/lib/python3.9/site-packages/ibmcloudant/__init__.py in <module>
     17 
     18 from ibm_cloud_sdk_core import IAMTokenManager, DetailedResponse, BaseService, ApiException, get_authenticator
---> 19 from .couchdb_session_authenticator import CouchDbSessionAuthenticator
     20 from .couchdb_session_get_authenticator_patch import new_construct_authenticator
     21 from .couchdb_session_base_service_patch import new_init, new_set_service_url, new_set_default_headers

/usr/lib/python3.9/site-packages/ibmcloudant/couchdb_session_authenticator.py in <module>
     20 
     21 from ibm_cloud_sdk_core.authenticators import Authenticator
---> 22 from .couchdb_session_token_manager import CouchDbSessionTokenManager
     23 
     24 

/usr/lib/python3.9/site-packages/ibmcloudant/couchdb_session_token_manager.py in <module>
     17 Module for managing session authentication token
     18 """
---> 19 from ibm_cloud_sdk_core.token_manager import TokenManager
     20 
     21 

ModuleNotFoundError: No module named 'ibm_cloud_sdk_core.token_manager'
```

**Expected behavior**
The import succedes. 

**Must gather (please complete the following information):**
 - SDK Version: latest release (3.11.2 for core, 0.0.35 for ibmcloudant)
 - Python Version: 3.9.6
 - Name of service that you're trying to use: any
 - Name of operation that you're trying to invoke: `import ibmcloudant`

**Additional context**
The import `from ibm_cloud_sdk_core.token_managers.token_manager import TokenManager` (instead of the currently used ` from ibm_cloud_sdk_core.token_manager import TokenManager` in couchdb_session_token_manager.py would work - and is probably what should be there?

**Comment by vmatyusGitHub** [comment]
Thank you for your report. 
This problem indeed exists and now is fixed in [commit-link](https://github.com/IBM/cloudant-python-sdk/commit/383c62a02c48b162635481cdf794ae23c00ccf75)), however not published. So there is no released version that contains this correction yet. The team is working hard to provide a new release version in August.
Can you share with us how urgent for you to have an official version with this fix?

**Comment by Patschke** [comment]
Thanks for the very fast response! 

It is not urgent at all (we are going to transition from the `couchdb` package to `ibmcloudant`, as the former is no longer maintained, but there is no hurry since the `couchdb` python package is currently still working. While in development we could in principle also just use the latest git versions instead of the releases). If I had noticed that this bug is fixed in the upstream repository, I'd not have created an issue at all - don't know why I didn't check that.

**Comment by ricellis** [comment]
Worth mentioning that a normal installation of `ibmcloudant` will get the core dependency version that we have declared in the requirements file. That is the version that we have tested and know is working i.e. `0.0.35` should be using core `3.10.1` - we specifically declare an exact version and not a range in our requirements to avoid this kind of break.
