### ISSUE TITLE
Cannot import Selector and FieldSort

### ISSUE THREAD

**Issue by kimlsalinas** [IBM/cloudant-python-sdk#140]
I'm want to use endpoint post_find, it requires having a Selector, and when I want to import it, it prompts an error, please advise. 

I'm importing as the documentation mentions 

`from ibmcloudant.cloudant_v1 import FieldSort, CloudantV1, Selector`

And the error messages are:
```
ImportError: cannot import name 'Selector' from 'ibmcloudant.cloudant_v1' 
ImportError: cannot import name 'FieldSort' from 'ibmcloudant.cloudant_v1'
```

Python version: 3.9.6

**Comment by emlaver** [comment]
@kimlsalinas thank you for finding this! This looks like it was added by mistake.  The `selector` is of type `dict` and the `sort` is `List[dict]`.  The below example should work correctly:
```
from ibmcloudant.cloudant_v1 import CloudantV1

service = CloudantV1.new_instance()

response = service.post_find(
  db='users',
  selector={'email_verified': {'$eq': True}},
  fields=["_id", "type", "name", "email"],
  sort=[{'name': 'desc'}],
  limit=3
).get_result()
print(response)
```
We'll update the example in the documentation.

**Comment by kimlsalinas** [comment]
thank you!
