### ISSUE TITLE
Add Python 3.10 to test matrix

### ISSUE THREAD

**Issue by ricellis** [IBM/cloudant-python-sdk#172]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add Python 3.10 to test matrix

**Describe alternatives you've considered**
N/A

**Additional context**
Add to `.travis.yml`

**Comment by mojito317** [comment]
https://docs.python.org/3/whatsnew/3.10.html says the release was today. Since that travis cannot handle Python 3.10 yet: https://app.travis-ci.com/github/IBM/cloudant-python-sdk/jobs/548514164#L163. We should postpone this. Till then I opened https://github.com/IBM/cloudant-python-sdk/pull/184 as a draft.

**Comment by ricellis** [comment]
@mojito317 there's a hot-tip in [this thread](https://travis-ci.community/t/add-python-3-10/12220) - sounds like we will need to use `"3.10"` not `3.10`

**Comment by ricellis** [comment]
The thread says 3.10.2 (also alias 3.10) is available for focal and bionic from 6 days ago.

So let's just remove the `dist` entry or bump it to one of those. I don't see any particular reason for us to be using something so old or tied to particular `dist` https://github.com/IBM/cloudant-python-sdk/blob/6790a0cdab6c83a342041d995656318893f8b59d/.travis.yml#L2

**Comment by eiri** [comment]
Confirmed this works with `focal`
- https://app.travis-ci.com/github/IBM/cloudant-python-sdk/jobs/556964957
```
$ python --version

Python 3.10.2
```
- https://github.com/IBM/cloudant-python-sdk/compare/add-python-310-to-matrix?expand=1

So should be possible with update that draft PR

**Comment by mojito317** [comment]
A simple remove did not work: https://github.com/IBM/cloudant-python-sdk/pull/184/commits/9ec4a09e42c3668f61e6bd7fa6e8ab2ef7bf9f7b

But with 'focal' it did: https://github.com/IBM/cloudant-python-sdk/pull/184/commits/d1755386f54800a189b6c3b75309b3f99ecbd74b

**Comment by mojito317** [comment]
the former in https://github.com/IBM/cloudant-python-sdk/pull/184/commits/6ca2679781e79c4f84f28e941fdeb04ff72e9313
The latter needs another PR, because that part is generated to the README.

**Comment by mojito317** [comment]
The PR about the readme: https://github.com/IBM/cloudant-python-sdk/pull/203/files
