### ISSUE TITLE
What is the default limit of results to be returned when running post_find?

### ISSUE THREAD

**Issue by digitalWestie** [IBM/cloudant-python-sdk#305]
When I run 'post_find' results are limited to 25 documents. Should I expect this?  Looking at [the docs](https://ibm.github.io/cloudant-python-sdk/docs/0.1.3/ibmcloudant.html?highlight=post_find#ibmcloudant.cloudant_v1.CloudantV1.post_find) I would have assumed it to be unlimited, unless this default limit is controlled by a server config somewhere? 

If not, and the default is 25, might be worth updating the docs to reflect this.

**Comment by ricellis** [comment]
It is indeed [a server configuration](https://docs.couchdb.org/en/3.2.2/config/query-servers.html#mango/default_limit) and  the default is [25 in CouchDB](https://docs.couchdb.org/en/3.2.2/api/database/find.html#post--db-_find).

Cloudant's limits are [documented here](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-limits#query-results).

**Comment by digitalWestie** [comment]
Thanks @ricellis , I think the default must have been bigger for couch 2. I recently upgraded to couch 3 and that's what brought the limit down.
