### ISSUE TITLE
Difference between Server and Database enforced for CouchDB

### ISSUE THREAD

**Issue by Patschke** [IBM/cloudant-python-sdk#344]
**Issue**

With previous versions the concepts of server and database url were to some degree interchangeable. Assume we have an couchDB server available at `https://example.com/couchdb-server` hosting various databases, among them `example-db`. Inside the database is a document called `awesome-doc`. With previous versions (1.x?) we could either use 
```python
db = ibmcloudant.CloudantV1(authenticator=ibm_cloud_sdk_core.authenticators.NoAuthAuthenticator())
db.set_service_url("https://example.com/couchdb-server/example-db")
doc = db.get_document("", "awesome-doc").get_result()
```
or
```python
db = ibmcloudant.CloudantV1(authenticator=ibm_cloud_sdk_core.authenticators.NoAuthAuthenticator())
db.set_service_url("https://example.com/couchdb-server")
doc = db.get_document("example-db", "awesome-doc").get_result()
```
The first option had the benefit, that it is less likely to mess up stuff by accident - as it limited the access to a specific database on the server. Has this been changed on purpose? Is there an easy way to restore the old behavior if it was?

**System Information:**
 - ibm-cloud-sdk-core version 3.16.0
 - cloudant-python-sdk version 0.2.1
 - Python Version 3.10.7
 - Fauxton on Apache CouchDB 2.2.0 

**Additional context**
We migrated from the python package `couchdb` to `ibmcloudant`, and everything is basically working just fine. This migration seems to be what is recommended as `couchdb` is not maintained anymore since early 2018. As we use a mixture of urls pointing to a specific database and urls pointing to our general server, it would be a convenient feature to continue using `ibmcloudant` in this way. If there is no such feature, we'd have to add an intermediate parsing step for our urls to check if they point to a server or a database (and store the database name for subsequent get/set/... calls in the later case).

**Comment by emlaver** [comment]
>Has this been changed on purpose?

Yes, `ibmcloudant` [0.2.1](https://github.com/IBM/cloudant-python-sdk/releases/tag/v0.2.1) brought in a new version of the core SDK dependency we use. That new version validates required path parameters are not empty (which brings python in line with all our other SDKs that did already correctly validate this). We consider it beneficial to fail such requests ahead of a server round-trip and to provide a more useful error message e.g. `db must be provided` instead of `405 method not allowed` when the request ends up at an unexpected path.
Note that we didn't mark this release version as a breaking change because in our experience requests would fail when reaching the server anyway.

>Is there an easy way to restore the old behavior if it was?

No, there is no easy way to restore.  I would recommend updating your urls to point to the server and extracting the database name.

**Comment by Patschke** [comment]
Thanks for the fast reply. I can assure you that for our setup the change is breaking and previously requests were not failing when reaching the server. I can see, that this might not be the expected usecases so we'll have to adapt to the new behavior. 

It's not trivial to tell if a url does reference a server or a database (some teams may have a server running at `https://example.com/cochdb-team-x` and others at `https://example.com/team-y/couchdb`, so from the url structure itself it's not clear either). So likely we'll have to connect to the server at the url provided to check if it's pointing at the server itself or a database on that server. I guess there is no recommended way to check this, if it wasn't supposed to be possible at all? For instance calls to `get_server_information()` do succeed in both cases, so one has to e.g. check for specific keys to exist. 

<details>
<summary>example from our test instance</summary>

```python
db.set_service_url('http://example.com/couchdb')

db.get_server_information().get_result()
{'couchdb': 'Welcome',
 'version': '2.2.0',
 'git_sha': '2a16ec4',
 'features': ['pluggable-storage-engines', 'scheduler'],
 'vendor': {'name': 'The Apache Software Foundation'}}

db.set_service_url('http://example.com/couchdb/test')

db.get_server_information().get_result()
{'db_name': 'test',
 'update_seq': '13-g1AAAAEzeJzLYWBg4MhgTmHgzcvPy09JdcjLz8gvLskBCjMlMiTJ____PyuREYeCJAUgmWQPVsOAS40DSE08fjUJIDX1YDVcONTksQBJhgYgBVQ2H7dZEHULIOr2E1J3AKLuPiF1DyDqgO5jygIAj_hjAw',
 'sizes': {'file': 1383085, 'external': 1728, 'active': 5226},
 'purge_seq': 0,
 'other': {'data_size': 1728},
 'doc_del_count': 1,
 'doc_count': 2,
 'disk_size': 1383085,
 'disk_format_version': 6,
 'data_size': 5226,
 'compact_running': False,
 'cluster': {'q': 8, 'n': 1, 'w': 1, 'r': 1},
 'instance_start_time': '0'}
```
</details>

Thanks again for developing this nice python API. We'll update our code to match the new behavior.
