### ISSUE TITLE
Bump sphinx to >=6 major version

### ISSUE THREAD

**Issue by mojito317** [IBM/cloudant-python-sdk#386]
From 6.0.0 sphinx the support for Python 3.7 is dropped. We should update to sphinx>=6.0.0 after we deprecated Python 3.7 which will be done presumably after 2023-06-27.

See https://github.com/IBM/cloudant-python-sdk/pull/384

As per comments below, this no longer depends on the Python 3.7 deprecation because we split the docs dependencies out.

**Comment by ricellis** [comment]
Isn't sphinx only used when building the docs? So it depends only on the version of python we use when we do that and package stuff (which IIRC is 3.10), _not_ the versions we support at runtime/test with.

Probably a better fix here is to separate sphinx/docs deps from those we use to test. Seems like the sort of thing facilitated by Python's dependency groups.

**Comment by ricellis** [comment]
The docs dependencies were split out in #491 so I think this no longer has a dependency on the runtime python version.

When we update sphinx we should also update myst-parser to 2.0.0 (i.e. redo #500)
