### ISSUE TITLE
Allow partition parameter in post_view

### ISSUE THREAD

**Issue by PPFilip** [IBM/cloudant-python-sdk#476]
**Is your feature request related to a problem? Please describe.**

I have a partitioned database, that uses partitioned views. These cannot be queried, because there is no partition parameter in post_view function, and I cannot craft a database name containing partition, as / gets escaped.

In other words, as of now we can only call 
`POST /my-database/_design/counter/_view/by_hour`
but we need
`POST /my-database/_partition/2023-04-20/_design/counter/_view/by_hour 200 ok 5`

**Describe the solution you'd like**

Being able to optionally make calls such as these
`xxx = couch_server.post_view(db=my_db, partition=db_partition, ddoc='counter', view='by_hour', group=True, key=db_key)`

In my local code, I can achieve it by adding the following to cloudant_v1.py definition of post_view

```
        if partition is None:
            path_param_keys = ['db', 'ddoc', 'view']
            path_param_values = self.encode_path_vars(db, ddoc, view)
            path_param_dict = dict(zip(path_param_keys, path_param_values))
            url = '/{db}/_design/{ddoc}/_view/{view}'.format(**path_param_dict)
        else:
            path_param_keys = ['db', 'ddoc', 'view', 'partition']
            path_param_values = self.encode_path_vars(db, ddoc, view, partition)
            path_param_dict = dict(zip(path_param_keys, path_param_values))
            url = '/{db}/_partition/{partition}/_design/{ddoc}/_view/{view}'.format(**path_param_dict)
```

As I understand, the file is auto generated so a PR would not do any good, and I am sure the code can be written in prettier way as well.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by ricellis** [comment]
The function you want is postPartitionView, docs:
https://github.com/IBM/cloudant-python-sdk/tree/main/examples#postpartitionview
