### ISSUE TITLE
Add docstring to custom files and functions

### ISSUE THREAD

**Issue by vmatyusGitHub** [IBM/cloudant-python-sdk#49]
**Is your feature request related to a problem?**
Currently, there are plenty of function without docstring. Before these lines the pylint is set disabled like: `# pylint: disable=missing-function-docstring`.
As a product of this, the generated doc has not so much content. Here is a snapshot:
![Screen Shot 2021-01-11 at 17 05 03](https://user-images.githubusercontent.com/26717393/104205860-2ec83180-542f-11eb-986a-84b1f0ef76ef.png)

**Describe the solution you'd like**
It would be good the add some description about the role of the functions and its parameters, additionally a little description about the module.

Here is a doc that can help in the syntax of the docstrings: https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html#the-sphinx-docstring-format
https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-python-objects

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ricellis** [comment]
Worth noting that none of that `common` module is intended to be user API so we should probably exlude them from the doc entirely or otherwise label it non-API.
