### ISSUE TITLE
Update starter python app with recommended IAM Method

### ISSUE THREAD

**Issue by movinglightspeed** [IBM/cloudant-python-sdk#50]
**Is your feature request related to a problem? Please describe.**
Yes, IBM Cloud recommends using IAM-only Cloudant instances not IAM + Legacy, however all starter applications such as 
https://github.com/IBM-Cloud/get-started-python use IAM Legacy method, a basic application that connects to a cloudant database on the IBM Cloud account using legacy credentials, none of them connect using IAM + Access token implementation that cloudant-python-sdk mentions and is recommended, though it's not clear because very easy to use the legacy credentials.

**Describe the solution you'd like**
If IAM only method for connecting to cloudant is recommended, please show in starter applications a implementation, because the starter applications show why the Legacy credentials for cloudant is the easier method and easier choice. I can easily pop in those creds and connect without issue, with IAM only, I have to use IAM API key and figure out a way to generate access token, trouble getting the access token to work with the IAM, how do I even go about it? No examples, I understand the security benefits but it is not at all easy for implementation.

**Describe alternatives you've considered**
+Use legacy credentials and generate new ones if there is a security breach.
+Applications that are connected on Cloud Foundry should not have to reference programatically cloudant credentials but should do this automagically on the backend, hence the connection between app and database.

**Additional context**
https://github.com/IBM-Cloud/get-started-python/blob/master/hello.py
IAM Legacy credentials examples are shown, but it's hard to see this cloudant python sdk implemented and it should be, as its recommended.

**Comment by emlaver** [comment]
@movinglightspeed thank you for bringing this to our attention.  The getting started tutorial in https://github.com/IBM-Cloud/get-started-python is not maintained or supported by our team.  Also, that tutorial is using our legacy [python-cloudant](https://github.com/cloudant/python-cloudant) library.  Please use your [existing ticket]( https://github.com/IBM-Cloud/get-started-python/issues/33) or a new ticket in the `get-started-python` repo to get support.

For more information on using IAM authentication in `cloudant-python-sdk`, see the [authentication section in our Cloudant API docs](https://cloud.ibm.com/apidocs/cloudant?code=python#authentication).
