### ISSUE TITLE
ViewQuery with Post_View_Query applies `reduce` even if  set to None

### ISSUE THREAD

**Issue by NielsKorschinsky** [IBM/cloudant-python-sdk#526]
**Describe the bug**

I was trying to use the `post_view_queries` method and got an `ApiException: query_parse_error, Code: 400`
There was no good error message, just the thing above.
Upon checking the http_response inside, I was able to get into the actual error reason:

```
'{"error":"query_parse_error","reason":"`include_docs` is invalid for reduce"}\n'
```

I did set the include_docs to true, however I left `reduce` as None, the default value.
Therefore, if not explicitly setting `reduce` to false, it is actually setting it to true.
I expect the opposite behavior, when using `None` to set it to false.

Once I manually set `reduce` to false, the query works.

**To Reproduce**

1. Create my instance, see #525 for the init issue:

```python 
basic_authenticator = BasicAuthenticator(
    username=self.__cloudant_config.cloudant_api_key,
    password=self.__cloudant_config.cloudant_secret
)
basic_authenticator.validate()

self.__client: CloudantV1 = CloudantV1.new_instance()
#
self.__client.authenticator = basic_authenticator
self.__client.set_service_url(self.__cloudant_config.cloudant_url)
```

2. Create the view Query, without setting `reduce`

```python
query = ViewQuery(
    include_docs = True,
    inclusive_end = False,
    limit = None,
    skip = None,
    end_key = ["2023","7","26"],
    start_key = ["2023","3","31"],
)
```

3. Run the query and get the error message as response

```python
test = self.__client.post_view_queries(
    db=self.__cloudant_config.cloudant_db,
    ddoc=self.__design_document,
    view=self.__view_name,
    queries=[query]
)
```

<img width="676" alt="image" src="https://github.com/IBM/cloudant-python-sdk/assets/49568673/975f7683-2aba-4c69-b303-c340044afdb8">

**Expected behavior**

The default behavior of `reduce=None` should be not using it

**Screenshots**

<img width="693" alt="image" src="https://github.com/IBM/cloudant-python-sdk/assets/49568673/b295768b-a153-4beb-aa13-2445b014e7aa">

**Must gather (please complete the following information):**
 - SDK Version [e.g. 1.2.1]
 - Python Version [e.g. Python 3.8]
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**

When setting `reduce` explicitly to false, it is working. None will default to True

**Comment by NielsKorschinsky** [comment]
I notice that I might have misunderstood the purpose of the `post_view_queries` and the `ViewQuery`.
My goal is that I have a design document with a view, where I have a date as key (list of int).

I want to query the data between two keys.

**Comment by NielsKorschinsky** [comment]
The documentation is saying:
> Parameter to specify whether to use the reduce function in a map-reduce view. Default is true when a reduce function is defined.

We did define a reduce function, therefore this is AS EXPECTED.
Feel free to close it, however I want to bring to attention that an inverted default would be more explanatory for new users.

**Comment by mojito317** [comment]
I think the original issue was using `include_docs=True` while you have a reduce function on your view description, and if you have one it is automatically set to true. By setting `reduce` to `false` you explicitly disable the `reduce` of your view and keep only the `map` part.

> Feel free to close it, however I want to bring to attention that an inverted default would be more explanatory for new users.

Yeah, you say something, I think the description could be more comprehensive.
