### ISSUE TITLE
Inconsitent Typing

### ISSUE THREAD

**Issue by NielsKorschinsky** [IBM/cloudant-python-sdk#527]
**Describe the bug**

Hi, 

This is more of a "Flavor" bug report, as I know the current existing syntax is allowed by some linters.
However, if using strict typing, the current way the methods are typed causes issues and enforces me to use `# type: ignore`, which is not preferable, as this will also disable actual type issues.

You are using method headers like:

```python

class ViewQuery: 
    def __init__(
        self,
        *,
        att_encoding_info: bool = None,
        attachments: bool = None,
        conflicts: bool = None,
        descending: bool = None,
        include_docs: bool = None,
        inclusive_end: bool = None,
        limit: int = None,
        skip: int = None,
        update_seq: bool = None,
        end_key: object = None,
        end_key_doc_id: str = None,
        group: bool = None,
        group_level: int = None,
        key: object = None,
        keys: List[object] = None,
        reduce: bool = None,
        stable: bool = None,
        start_key: object = None,
        start_key_doc_id: str = None,
        update: str = None,
    ) -> None:
```

The issue is, that you have there elements like `limit: int = None,`
This already conflicts, as limit is not set to be an `Optional[int]`.
If using an optional int to access this method, my linter is correctly showing me an issue, as the types conflict.

If used correctly, either the type should be all changed to Optional, or the provided value should be the correct value to disable/default behavior of said argument.

**To Reproduce**

1. Use a linter on strict settings.
2. Try not to use the `limit` argument, therefore setting it to None
3. Linter shows error

<img width="754" alt="image" src="https://github.com/IBM/cloudant-python-sdk/assets/49568673/c6d4a7b4-3b9f-4e9b-9ad5-22d0c2c9180b">

 
<img width="754" alt="image" src="https://github.com/IBM/cloudant-python-sdk/assets/49568673/76caeace-ad30-48bf-89cb-2b164f27313c">

**Expected behavior**

The method header is either has the correct types or uses default/disable values which fits the expected types.

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Version [e.g. 1.2.1]
 - Python Version [e.g. Python 3.8]
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**

**Comment by NielsKorschinsky** [comment]
I want also to use this issue report to highlight that I really like the fact that typing was applied at all and the way you can interact with the API seem very smooth and nice. Thanks a lot for providing the API!

**Comment by mojito317** [comment]
Hi @NielsKorschinsky! FYI: The typing was improved on our latest (v0.7.0) version.
