### ISSUE TITLE
provide advanced query example 

### ISSUE THREAD

**Issue by carlobongiovanni** [IBM/cloudant-python-sdk#528]
Hi, my cloudant db is polluted with documents having a custom field which sometimes is empty (due to wrong import batches), see this example document:
```{'id': '0aa8a992c5b4b735aeab87ddbaade6c8', 'key': '0aa8a992c5b4b735aeab87ddbaade6c8', 'value': {'rev': '1-1b3be32d43b540795c44c7a1a68b37fe'}, 'doc': {'_id': '0aa8a992c5b4b735aeab87ddbaade6c8', '_rev': '1-1b3be32d43b540795c44c7a1a68b37fe', 'field1': '141cc8d0-15c7-11ee-b9ee-17283b34d66e'}, field2: ""}```

I would like to exclude this document from my queries, and I'm trying the [postAllDocsQueries](https://github.com/IBM/cloudant-python-sdk/tree/main/examples#postalldocsqueries) which in theory could help me. If that's the case, how would I represent the missing field in the query? Which sintax is the query using? Now I'm playing with something like this:
```
all_docs_query_field2 = AllDocsQuery(
    keys=['field2:*']
)
res = self.client.post_all_docs_queries(db=self.database, queries=[all_docs_query_field2]).get_result()
```

Thanks
C.

**Comment by emlaver** [comment]
Hello @carlobongiovanni, I'd recommend using a view to exclude these empty fields.  You'd need to first create a design document with a view: https://github.com/IBM/cloudant-python-sdk/tree/main/examples#putdesigndocument

Your `DesignDocumentViewsMapReduce` object could look like the code below to omit docs that contain an empty `field2` key:
```python
email_view_map_reduce = DesignDocumentViewsMapReduce(
  map='function(doc) { if(doc.field2){\n  emit(doc.field2, [doc._id]) }}'
)
```
After creating the design document with the view, you can query using [postView](https://github.com/IBM/cloudant-python-sdk/tree/main/examples#postview).

Additional resources:
- Creating a view: https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-creating-views-mapreduce
- Using views: https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-using-views

**Comment by carlobongiovanni** [comment]
hi @emlaver thanks for answering, but I don't want to exclude a key, I want to exclude a document from the query, when that key is present but has empty value.

**Comment by emlaver** [comment]
Hi @carlobongiovanni the map function I suggested above will exclude the documents when you query the view.  I updated my original comment to reflect this.
