### ISSUE TITLE
Documentation discrepancy

### ISSUE THREAD

**Issue by rmhowe425** [IBM/cloudant-python-sdk#608]
**Describe the bug**
The documentation for `put_document` and `post_document` in cloudant_v1.py appears to be the same. The in-line documentation for both methods state "Create or modify a document.". 

I am assuming that `put_document` should create a document, and `post_document` should update a document.

**To Reproduce**
N/A: This Issue is for a potential documentation discrepancy.

**Expected behavior**

- The in-line method documentation for `put_document()` is updated to reflect that the method should be called to update and existing document.
- The in-line method documentation for `post_docutment()` is updated to reflect that the method should be called to create a new document.

**Screenshots**
![image](https://github.com/IBM/cloudant-python-sdk/assets/45905457/c2c51324-89c8-4e02-ac1e-e68ddc4a8735)
![image](https://github.com/IBM/cloudant-python-sdk/assets/45905457/2668b54a-97af-4c92-b191-4ca877bf13c9)

**Must gather (please complete the following information):**
 - SDK Version: ibmcloudant>=0.4.1
 - Python Version:  Python 3.10
 - Name of service that you're trying to use: N/a
 - Name of operation that you're trying to invoke: N/A

**Additional context**
I would love to submit a PR to fix this discepancy, assuming that it is one. 

Were you able to avoid the problem by changing your application code slightly? --> YES

**Comment by mojito317** [comment]
Hi @rmhowe425! Both `post_document` and `put_document` can be used to create or modify a document.

The reason we have both is to match the CouchDB API where `post_document` is identical with the `POST /$DATABASE` request while `put_document` is identical with `PUT /$DATABASE/$DOC_ID`.

The main difference is in `put_document` you can explicitly define the (optional) revision and the (required) id of the document, while in `post_document` you can do it inside the supplied JSON document, as the documentation highlights.

Please check the [Create a database and add a document](https://github.com/IBM/cloudant-python-sdk?tab=readme-ov-file#1-create-a-database-and-add-a-document) and [Update your previously created document](https://github.com/IBM/cloudant-python-sdk?tab=readme-ov-file#3-update-your-previously-created-document) examples in our README particularly to the commented out `put_document` alternatives.
