### ISSUE TITLE
ChangesFollower does not get changes _since when the option is supplied

### ISSUE THREAD

**Issue by kingraphaii** [IBM/cloudant-python-sdk#728]
**Describe the bug**

I tried to use the `ChangesFollower` api by fetching changes "once off" and supplying the `since` option since I save the last one after each query onto some persisted storage.

Here is a snippet of my code:

```py
previously_persisted_seq = CouchHelper.get_previously_persisted_seq()
# example seq returned: 12-g1AAAACLeJzLYWBgYMpgTmHgzcvPy09JdcjLz8gvLskBCScyJNX___8_K4M5kScXKMBuaZFslmqQiK4Yh_Y8FiDJ0ACk_kNNYQCbkpRqkZRiYo6uJwsAX0Aq9g

cf_options = {'db': 'redacted_db_name', 'include_docs': True, 'since': previously_persisted_seq}
changes_follower = ChangesFollower(service=helper.client, **cf_options)
changes_items = changes_follower.start_one_off()
for change in changes_items:
   # this is where I save each change to external storage
```

**To Reproduce**

1. Retrieve the last sequence ID.
2. Create `cf_options` with since set to the last sequence ID.
3. Instantiate ChangesFollower with the provided options.
4. Call start_one_off() on the ChangesFollower instance.
5. Observe that all changes are fetched from the beginning rather than from the specified sequence.

**Expected behavior**
The ChangesFollower API should start fetching changes from the specified since sequence, rather than reloading all changes from the beginning.

**Screenshots**

**Must gather (please complete the following information):**
 - SDK Versions:
   - `ibm-cloud-sdk-core==3.21.0`
   - `ibmcloudant==0.9.2`
 - Python Version: `Python 3.10.14`
 - Name of service that you're trying to use: `Changes feed follower (beta)`
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**
When I use the `post_changes` api directly, I am able to only get the changes since the desired checkpoint

![image](https://github.com/user-attachments/assets/6e9fd460-f3fa-40d0-9664-af5ce963fbf5)

**Comment by ricellis** [comment]
Thanks for the bug report, I was able to reproduce the issue - we will work on a fix.
